### PR TITLE
added docker compose example to README

### PR DESCRIPTION
**Pull request by ZachMyers3**
See title, I struggled to get this up and running so I thought I'd share my solution to help others in the future!

Happy to change as needed.

### CODE REVIEW

**Comment by ZachMyers3** [comment]
I have format on save enabled and it made some changes to this file as well. If you'd like me to revert those changes I can do so as well.

**Comment by izderadicka** [comment]
Formatting is fine,  someone finally made cleanup of readme:-) Thanks for that.
Before merging just wanted to be sure that shared secret in you example is dummy?

**Comment by ZachMyers3** [comment]
Yes of course! I can simplify it if it helps readability too.

**Comment by izderadicka** [comment]
Merged, thank you for your contribution.

**Pull request merged**
